load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.0"

RULES_JVM_EXTERNAL_SHA = "31701ad93dbfe544d597dbe62c9a1fdd76d81d8a9150c2bf1ecf928ecdf97169"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

local_repository(
    name = "rules_jooq_codegen",
    path = "../../",
)

JOOQ_VERSION = "3.14.4"

maven_install(
    artifacts = [
        "org.jooq:jooq:%s" % JOOQ_VERSION,
        "org.jooq:jooq-meta:%s" % JOOQ_VERSION,
        "org.jooq:jooq-codegen:%s" % JOOQ_VERSION,
        "mysql:mysql-connector-java:8.0.22",
        "org.testcontainers:testcontainers:1.15.1",
        "org.testcontainers:mysql:1.15.1",
        "org.liquibase:liquibase-core:4.2.2",
    ],
    maven_install_json = "@//:maven_install.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)

load("@maven//:defs.bzl", "pinned_maven_install")

pinned_maven_install()
